"""CDSCO Regulatory Intelligence Repository — realistic mock seed built to
mirror CDSCO's monthly NSQ, Spurious, Recall and Theft/Diversion advisories.
Loaded on startup alongside the medicine catalog. Real datasets can be dropped
into the same collection later without refactor — the schema is stable."""

CDSCO_ENTRIES = [
    # ---------- CRITICAL · Spurious Drug Alerts (Risk 95–100) ----------
    {
        "alert_category": "Spurious",
        "product_name": "Telma 40",
        "generic_composition": "Telmisartan 40mg",
        "batch_number": "05240226",
        "manufacturer": "Glenmark Pharmaceuticals Ltd.",
        "failure_reason": "Dissolution Failure — active ingredient below declared limit",
        "reporting_authority": "CDSCO Central Drugs Laboratory",
        "reporting_lab": "CDL Kolkata",
        "reporting_date": "2025-11-14",
        "risk_score": 98,
    },
    {
        "alert_category": "Spurious",
        "product_name": "Pan 40",
        "generic_composition": "Pantoprazole 40mg",
        "batch_number": "PAN23881",
        "manufacturer": "Alkem Laboratories Ltd.",
        "failure_reason": "Assay failure — spurious labelling detected",
        "reporting_authority": "CDSCO",
        "reporting_lab": "RDTL Guwahati",
        "reporting_date": "2025-10-02",
        "risk_score": 97,
    },
    {
        "alert_category": "Spurious",
        "product_name": "Amoxil 500mg",
        "generic_composition": "Amoxicillin 500mg",
        "batch_number": "AMX00492",
        "manufacturer": "GlaxoSmithKline Pharmaceuticals Ltd.",
        "failure_reason": "Failed dissolution test — sub-therapeutic release",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Chennai",
        "reporting_date": "2025-10-18",
        "risk_score": 96,
    },
    {
        "alert_category": "Spurious",
        "product_name": "Crocin Advance",
        "generic_composition": "Paracetamol 500mg",
        "batch_number": "CRO24501",
        "manufacturer": "GlaxoSmithKline Consumer Healthcare",
        "failure_reason": "Foil labelling mismatch with batch registry",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Mumbai",
        "reporting_date": "2025-12-05",
        "risk_score": 95,
    },
    {
        "alert_category": "Spurious",
        "product_name": "Combiflam",
        "generic_composition": "Ibuprofen + Paracetamol",
        "batch_number": "CBF23108",
        "manufacturer": "Sanofi India Ltd.",
        "failure_reason": "Manufacturing site not authorised — packaging mismatch",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Kolkata",
        "reporting_date": "2025-08-22",
        "risk_score": 99,
    },
    # ---------- CRITICAL · Recall Alerts (Risk 95–100) ----------
    {
        "alert_category": "Recall",
        "product_name": "Dolo 650",
        "generic_composition": "Paracetamol 650mg",
        "batch_number": "PCM240721",
        "manufacturer": "Micro Labs Ltd.",
        "failure_reason": "Spurious content — quality alert Class II",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Kolkata",
        "reporting_date": "2025-11-04",
        "risk_score": 98,
    },
    {
        "alert_category": "Recall",
        "product_name": "Ranitidine 150mg",
        "generic_composition": "Ranitidine 150mg",
        "batch_number": "RTC90021",
        "manufacturer": "Cipla Ltd.",
        "failure_reason": "NDMA impurity above safe limits",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Mumbai",
        "reporting_date": "2025-09-02",
        "risk_score": 97,
    },
    {
        "alert_category": "Recall",
        "product_name": "Losar 50",
        "generic_composition": "Losartan 50mg",
        "batch_number": "LSR00815",
        "manufacturer": "Unichem Laboratories Ltd.",
        "failure_reason": "Nitrosamine contamination — recall Class II",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Kolkata",
        "reporting_date": "2025-12-11",
        "risk_score": 96,
    },
    {
        "alert_category": "Recall",
        "product_name": "Metformin GP 500",
        "generic_composition": "Metformin HCl 500mg",
        "batch_number": "MET55003",
        "manufacturer": "USV Pvt. Ltd.",
        "failure_reason": "Suspected counterfeit foil packaging — recall issued",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Chennai",
        "reporting_date": "2026-01-08",
        "risk_score": 96,
    },
    {
        "alert_category": "Recall",
        "product_name": "Cardace 5",
        "generic_composition": "Ramipril 5mg",
        "batch_number": "CRD24019",
        "manufacturer": "Sanofi India Ltd.",
        "failure_reason": "Impurity level exceeds pharmacopoeia limits",
        "reporting_authority": "CDSCO",
        "reporting_lab": "CDL Mumbai",
        "reporting_date": "2026-01-19",
        "risk_score": 95,
    },
    # ---------- QUALITY RISK · NSQ (Risk 80–90) ----------
    {
        "alert_category": "NSQ",
        "product_name": "Azithral 500",
        "generic_composition": "Azithromycin 500mg",
        "batch_number": "AZT24118",
        "manufacturer": "Alembic Pharmaceuticals Ltd.",
        "failure_reason": "Uniformity of content — Not of Standard Quality",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Bengaluru",
        "reporting_date": "2025-12-02",
        "risk_score": 86,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Levoflox 500",
        "generic_composition": "Levofloxacin 500mg",
        "batch_number": "LVF24009",
        "manufacturer": "Torrent Pharmaceuticals Ltd.",
        "failure_reason": "Description — coating discolouration observed",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Ahmedabad",
        "reporting_date": "2026-01-04",
        "risk_score": 82,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Pantop 40",
        "generic_composition": "Pantoprazole 40mg",
        "batch_number": "PTP24506",
        "manufacturer": "Aristo Pharmaceuticals Pvt. Ltd.",
        "failure_reason": "Assay — active content 92.4% (spec 95–105%)",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Hyderabad",
        "reporting_date": "2025-11-27",
        "risk_score": 88,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Concor 5",
        "generic_composition": "Bisoprolol 5mg",
        "batch_number": "CNC24022",
        "manufacturer": "Merck Ltd.",
        "failure_reason": "Related substance — impurity B above 0.5% limit",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Chandigarh",
        "reporting_date": "2025-12-14",
        "risk_score": 84,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Ecosprin 75",
        "generic_composition": "Aspirin 75mg",
        "batch_number": "ECO24807",
        "manufacturer": "USV Pvt. Ltd.",
        "failure_reason": "Disintegration time above pharmacopoeia limit",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Mumbai",
        "reporting_date": "2026-01-11",
        "risk_score": 81,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Rosuvas 10",
        "generic_composition": "Rosuvastatin 10mg",
        "batch_number": "RSV24102",
        "manufacturer": "Sun Pharmaceutical Industries Ltd.",
        "failure_reason": "Dissolution — 68% released at 30 min (spec ≥75%)",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Kolkata",
        "reporting_date": "2025-10-29",
        "risk_score": 89,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Thyronorm 100mcg",
        "generic_composition": "Levothyroxine 100mcg",
        "batch_number": "THY24045",
        "manufacturer": "Abbott India Ltd.",
        "failure_reason": "Uniformity of dosage units — outside limit",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Mumbai",
        "reporting_date": "2025-12-19",
        "risk_score": 85,
    },
    {
        "alert_category": "NSQ",
        "product_name": "Amlokind 5",
        "generic_composition": "Amlodipine 5mg",
        "batch_number": "AMK24211",
        "manufacturer": "Mankind Pharma Ltd.",
        "failure_reason": "Assay 91.8% — Not of Standard Quality",
        "reporting_authority": "State Drug Control Administration",
        "reporting_lab": "SDL Delhi",
        "reporting_date": "2026-01-22",
        "risk_score": 83,
    },
    # ---------- THEFT / DIVERSION ALERTS (Risk 95–100) ----------
    {
        "alert_category": "Theft",
        "product_name": "Foracort 200 Inhaler",
        "generic_composition": "Formoterol + Budesonide",
        "batch_number": "FCT23709",
        "manufacturer": "Cipla Ltd.",
        "failure_reason": "Consignment diverted from cold-chain — advisory issued",
        "reporting_authority": "CDSCO Vigilance Cell",
        "reporting_lab": "CDSCO Zonal Office Mumbai",
        "reporting_date": "2025-11-08",
        "risk_score": 96,
    },
    {
        "alert_category": "Theft",
        "product_name": "Januvia 100",
        "generic_composition": "Sitagliptin 100mg",
        "batch_number": "JVA23044",
        "manufacturer": "MSD Pharmaceuticals Pvt. Ltd.",
        "failure_reason": "Stolen consignment traced — do not accept batch",
        "reporting_authority": "CDSCO Vigilance Cell",
        "reporting_lab": "CDSCO Zonal Office Kolkata",
        "reporting_date": "2025-12-16",
        "risk_score": 98,
    },
    {
        "alert_category": "Theft",
        "product_name": "Seroflo 250 Inhaler",
        "generic_composition": "Salmeterol + Fluticasone",
        "batch_number": "SFL24007",
        "manufacturer": "Cipla Ltd.",
        "failure_reason": "Diversion advisory — batches missing from distribution",
        "reporting_authority": "CDSCO Vigilance Cell",
        "reporting_lab": "CDSCO Zonal Office Bengaluru",
        "reporting_date": "2026-01-15",
        "risk_score": 95,
    },
]


def risk_bucket(score: int) -> tuple[str, str]:
    """Return (severity, headline) for a given risk score."""
    if score >= 95:
        return ("Critical", "Critical Regulatory Alert")
    if score >= 80:
        return ("Quality Risk", "NSQ / Quality Risk")
    return ("Clear", "No Regulatory Alert Found")


def normalize_batch(raw: str) -> str:
    """Uppercase + strip whitespace/hyphens/dots for tolerant matching."""
    if not raw:
        return ""
    keep = [c for c in raw.upper() if c.isalnum()]
    return "".join(keep)
